### ISSUE TITLE
Broken positioning of Panel with Initial width and height

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/react-geo#863] opened 2018-09-05 07:45 UTC
In the documentation a `Panel` with `width` and `height` props is positioned wrong:

![broken_panel](https://user-images.githubusercontent.com/1849416/45078136-787e1000-b0ef-11e8-86a1-94c99866ad61.png)

It should be in the white box above "View Code". We need to check if this happens in real applications, too.

@PeterC66 mentioned this in #861. Thanks.

**Comment by dnlkoch** [comment] 2018-09-05 08:03
It may be related to the issue discussed in #812.

**Comment by annarieger** [comment] 2018-09-05 08:16
it **is** related to #812 and caused by update of `rnd` dependency.

**Comment by marcjansen** [comment] 2018-09-22 21:36
we have a fix now, right? can we close this?

**Comment by annarieger** [comment] 2018-09-24 10:20
Which fix do you mean @marcjansen?

If that one from #812, then I would prefer to keep this issue open since the [solution](https://github.com/terrestris/react-geo/pull/811/commits/21e18f27e84099a6b3128f3290e9b6857caa2399) introduced there concerns example only but not the `Panel` and `Window` component itself.

Just checked shortly, `rnd` package was not released any more after this issue was observed while using `react-geo`. So I guess the problem is still not solved.

**Comment by LukasLohoff** [comment] 2018-10-01 14:37
I've also got a strange problem with a react-geo `Window` and `Panel`. The `Window` is positioned incorrectly. Additionally, when both are open at the same time and change the the `Window` position, the `Panel` moves as well

I think this is related to this issue, correct me if I'm wrong

**Comment by marcjansen** [comment] 2018-10-23 16:11
I think react-rnd is now at `v9.0.2`, right? any chance we can upgrade again to fix this?

**Comment by marcjansen** [comment] 2018-11-19 22:52
I still see this. What can we do about this?

**Closed** 2022-03-03 10:52 UTC
Labels: bug, documentation
